--------------------------------------------------------
--  File created - понедельник-ќкт€брь-05-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CLIENTCARD
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CLIENTCARD" 
   (	"ID" VARCHAR2(20 BYTE), 
	"MAKE" DATE, 
	"MODEL" VARCHAR2(20 BYTE), 
	"YEAR" NUMBER(20,0), 
	"VIN" VARCHAR2(20 BYTE), 
	"ID_CARD" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CLIENTS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CLIENTS" 
   (	"ID" VARCHAR2(20 BYTE), 
	"FIRSTNAME" VARCHAR2(20 BYTE), 
	"LASTNAME" VARCHAR2(20 BYTE), 
	"PHONE" NUMBER, 
	"EMAIL" VARCHAR2(20 BYTE), 
	"DDATE" DATE, 
	"ADDRESS" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LISTOFORDERS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."LISTOFORDERS" 
   (	"ID_CARD" VARCHAR2(20 BYTE), 
	"DATEO" DATE, 
	"ORDER_AMOUNT" NUMBER(20,0), 
	"ORDER_STATUS" VARCHAR2(20 BYTE), 
	"ID_ORDER" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.CLIENTCARD
SET DEFINE OFF;
Insert into SYSTEM.CLIENTCARD (ID,MAKE,MODEL,YEAR,VIN,ID_CARD) values ('1',to_date('12.10.99','DD.MM.RR'),'BMW','2000','VB354','1a');
Insert into SYSTEM.CLIENTCARD (ID,MAKE,MODEL,YEAR,VIN,ID_CARD) values ('2',to_date('10.10.03','DD.MM.RR'),'KTM','2005','VC013','3a');
Insert into SYSTEM.CLIENTCARD (ID,MAKE,MODEL,YEAR,VIN,ID_CARD) values ('1',to_date('11.11.05','DD.MM.RR'),'AUDI','2007','VG123','2a');
Insert into SYSTEM.CLIENTCARD (ID,MAKE,MODEL,YEAR,VIN,ID_CARD) values ('3',to_date('10.10.00','DD.MM.RR'),'SUZUKI','2000','VB775','4a');
Insert into SYSTEM.CLIENTCARD (ID,MAKE,MODEL,YEAR,VIN,ID_CARD) values ('1',to_date('03.10.15','DD.MM.RR'),'Volvo','1988','gh4','8a');
REM INSERTING into SYSTEM.CLIENTS
SET DEFINE OFF;
Insert into SYSTEM.CLIENTS (ID,FIRSTNAME,LASTNAME,PHONE,EMAIL,DDATE,ADDRESS) values ('1','Vasia','Pupkin','37544753','pupkin.com',null,null);
Insert into SYSTEM.CLIENTS (ID,FIRSTNAME,LASTNAME,PHONE,EMAIL,DDATE,ADDRESS) values ('2','Anton','Papaikin','34623423','papaikin.com',null,null);
Insert into SYSTEM.CLIENTS (ID,FIRSTNAME,LASTNAME,PHONE,EMAIL,DDATE,ADDRESS) values ('3','Leva','Sobaka','34324','leva.com',null,null);
Insert into SYSTEM.CLIENTS (ID,FIRSTNAME,LASTNAME,PHONE,EMAIL,DDATE,ADDRESS) values ('8','neyjeli','ae','33443','gav.com',to_date('03.10.15','DD.MM.RR'),null);
Insert into SYSTEM.CLIENTS (ID,FIRSTNAME,LASTNAME,PHONE,EMAIL,DDATE,ADDRESS) values ('25','gamunkul','ase','334343','gav.com',to_date('04.10.15','DD.MM.RR'),'gadga');
Insert into SYSTEM.CLIENTS (ID,FIRSTNAME,LASTNAME,PHONE,EMAIL,DDATE,ADDRESS) values ('234','asd','asd','334343','gav.com',to_date('04.10.15','DD.MM.RR'),'gadga');
Insert into SYSTEM.CLIENTS (ID,FIRSTNAME,LASTNAME,PHONE,EMAIL,DDATE,ADDRESS) values ('230','gamunkul','ase','334343','gav.com',to_date('04.10.15','DD.MM.RR'),'gadga');
Insert into SYSTEM.CLIENTS (ID,FIRSTNAME,LASTNAME,PHONE,EMAIL,DDATE,ADDRESS) values ('228','opiat','davd','334343','gav.com',to_date('04.10.15','DD.MM.RR'),'gadga');
Insert into SYSTEM.CLIENTS (ID,FIRSTNAME,LASTNAME,PHONE,EMAIL,DDATE,ADDRESS) values ('1086',null,null,'0',null,to_date('12.08.61','DD.MM.RR'),null);
Insert into SYSTEM.CLIENTS (ID,FIRSTNAME,LASTNAME,PHONE,EMAIL,DDATE,ADDRESS) values ('18','gamunkul','ase','334343','gav.com',to_date('04.10.15','DD.MM.RR'),'gadga');
Insert into SYSTEM.CLIENTS (ID,FIRSTNAME,LASTNAME,PHONE,EMAIL,DDATE,ADDRESS) values ('19','gamunkul','ase','0',null,null,null);
Insert into SYSTEM.CLIENTS (ID,FIRSTNAME,LASTNAME,PHONE,EMAIL,DDATE,ADDRESS) values ('1213','Vasilii','Pupkin','32123412','gaav@gav.com',to_date('28.08.66','DD.MM.RR'),'Pupkino');
Insert into SYSTEM.CLIENTS (ID,FIRSTNAME,LASTNAME,PHONE,EMAIL,DDATE,ADDRESS) values ('1947','Ivan','Ivanovich','347635278','gav@com',to_date('12.12.22','DD.MM.RR'),'Minsk');
REM INSERTING into SYSTEM.LISTOFORDERS
SET DEFINE OFF;
Insert into SYSTEM.LISTOFORDERS (ID_CARD,DATEO,ORDER_AMOUNT,ORDER_STATUS,ID_ORDER) values ('1a',to_date('03.10.15','DD.MM.RR'),'300','Complete','b1');
--------------------------------------------------------
--  Constraints for Table CLIENTCARD
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CLIENTCARD" ADD CONSTRAINT "CLIENTCARD_PK" PRIMARY KEY ("ID_CARD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."CLIENTCARD" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."CLIENTCARD" MODIFY ("MAKE" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."CLIENTCARD" MODIFY ("MODEL" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."CLIENTCARD" MODIFY ("YEAR" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."CLIENTCARD" MODIFY ("VIN" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."CLIENTCARD" MODIFY ("ID_CARD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENTS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CLIENTS" ADD CONSTRAINT "CLIENTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."CLIENTS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LISTOFORDERS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."LISTOFORDERS" ADD CONSTRAINT "LISTOFORDERS_PK" PRIMARY KEY ("ID_ORDER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."LISTOFORDERS" MODIFY ("ID_CARD" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."LISTOFORDERS" MODIFY ("DATEO" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."LISTOFORDERS" MODIFY ("ORDER_AMOUNT" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."LISTOFORDERS" MODIFY ("ORDER_STATUS" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."LISTOFORDERS" MODIFY ("ID_ORDER" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CLIENTCARD
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CLIENTCARD" ADD CONSTRAINT "CLIENTCARD_CLIENTS_FK1" FOREIGN KEY ("ID")
	  REFERENCES "SYSTEM"."CLIENTS" ("ID") ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table LISTOFORDERS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."LISTOFORDERS" ADD CONSTRAINT "LISTOFORDERS_CLIENTCARD_FK1" FOREIGN KEY ("ID_CARD")
	  REFERENCES "SYSTEM"."CLIENTCARD" ("ID_CARD") ENABLE;
